export enum DeliveryType {
  PAPER = 'PAPER',

  EMAIL = 'EMAIL',

  SMS = 'SMS',

  EMAIL_OR_SMS = 'EMAIL_OR_SMS',

  EMAIL_AND_SMS = 'EMAIL_AND_SMS',

  PAPER_AND_EMAIL = 'PAPER_AND_EMAIL',

  PAPER_AND_SMS = 'PAPER_AND_SMS',

  PAPER_AND_EMAIL_OR_SMS = 'PAPER_AND_EMAIL_OR_SMS',

  PAPER_AND_EMAIL_AND_SMS = 'PAPER_AND_EMAIL_AND_SMS',
}
